apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-policy-dummy-config
  namespace: kube-system
data:
  require-queue-name: "audit"
  description: "Dummy Kyverno policy configuration for CTK shared cluster validation"
