apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: tpuv6e-shared-flavor
spec:
  nodeLabels:
    cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
  tolerations:
    - effect: NoSchedule
      key: google.com/tpu
      value: "present"
