apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: tpu7x-shared-flavor
spec:
  nodeLabels:
    cloud.google.com/gke-tpu-accelerator: tpu7x
  tolerations:
    - effect: NoSchedule
      key: google.com/tpu
      value: "present"
